package harness

var All = map[string]Harness{
	"claude": {
		Name: "claude", Binary: "claude",
		Install:  []string{"npm install -g @anthropic-ai/claude-code"},
		APIFormat: Anthropic, EndpointEnvVar: "ANTHROPIC_BASE_URL", APIKeyEnvVar: "ANTHROPIC_API_KEY",
		DefaultModel: "claude-haiku-4-5-20251001",
		HookFormat: JSONNested, EventCase: PascalCase,
		HookConfigDir: ".claude",
		Events: Events{
			SessionStart: "SessionStart", PromptSubmit: "UserPromptSubmit",
			PreToolUse: "PreToolUse", PostToolUse: "PostToolUse",
			Stop: "Stop", PreCompact: "PreCompact", SessionEnd: "SessionEnd",
		},
		SkillsDir:          ".claude/skills",
		HeadlessCmd:         []string{"claude", "-p"},
		HeadlessExtraFlags:  []string{"--dangerously-skip-permissions"},
		NeedsGitRepo:        true,
		NeedsNonRoot:        true,
		HooksInHeadless:     true,
		InteractiveCmd:      []string{"claude"},
		ExitCommand:         "/exit",
		HooksInInteractive:  true,
		CanInject:           true,
		InjectionMethod:     "stdout → system-reminder",
	},
	"codex": {
		Name: "codex", Binary: "codex",
		Install:  []string{"npm install -g @openai/codex"},
		APIFormat: Responses, EndpointEnvVar: "", APIKeyEnvVar: "OPENAI_API_KEY",
		ModelFlag: "-c model=", DefaultModel: "gpt-4o-mini",
		HookFormat: JSONNested, EventCase: PascalCase,
		HookConfigDir: ".codex",
		Events: Events{
			SessionStart: "SessionStart", PromptSubmit: "UserPromptSubmit",
			Stop: "Stop",
		},
		SkillsDir:           ".agents/skills",
		HeadlessCmd:          []string{"codex", "exec"},
		HeadlessExtraFlags:   []string{"--dangerously-bypass-hook-trust"},
		NeedsGitRepo:         true,
		HooksInHeadless:      true,
		InteractiveCmd:       []string{"codex"},
		ExitCommand:          "/exit",
		HooksInInteractive:   true,
		CanInject:            true,
		InjectionMethod:      "stdout → context",
	},
	"copilot": {
		Name: "copilot", Binary: "copilot",
		Install:  []string{"npm install -g @github/copilot"},
		APIFormat: OpenAI, EndpointEnvVar: "COPILOT_PROVIDER_BASE_URL", APIKeyEnvVar: "COPILOT_PROVIDER_API_KEY",
		DefaultModel: "gpt-4o-mini",
		HookFormat: JSONCopilot, EventCase: CamelCase,
		HookConfigDir: ".copilot/hooks",
		Events: Events{
			SessionStart: "sessionStart", PromptSubmit: "userPromptSubmitted",
			PreToolUse: "preToolUse", PostToolUse: "postToolUse",
			Stop: "agentStop", SessionEnd: "sessionEnd",
		},
		SkillsDir:           ".copilot/skills",
		HeadlessCmd:          []string{"copilot", "--prompt"},
		HooksInHeadless:      true,
		InteractiveCmd:       []string{"copilot"},
		ExitCommand:          "/exit",
		HooksInInteractive:   true,
		CanInject:            true,
		InjectionMethod:      `{"additionalContext":"..."}`,
	},
	"grok": {
		Name: "grok", Binary: "grok",
		Install:  []string{"curl -fsSL https://x.ai/cli/install.sh | bash"},
		APIFormat: OpenAI, EndpointEnvVar: "GROK_CLI_CHAT_PROXY_BASE_URL", APIKeyEnvVar: "XAI_API_KEY",
		DefaultModel: "grok-3-mini",
		HookFormat: JSONNested, EventCase: PascalCase,
		HookConfigDir: ".grok/hooks",
		Events: Events{
			SessionStart: "SessionStart", PromptSubmit: "UserPromptSubmit",
			PreToolUse: "PreToolUse", PostToolUse: "PostToolUse",
			Stop: "Stop", PreCompact: "PreCompact", SessionEnd: "SessionEnd",
		},
		SkillsDir:            ".grok/skills",
		HeadlessCmd:           []string{"grok", "-p"},
		HooksInHeadless:       false,
		InteractiveCmd:        []string{"grok", "--always-approve"},
		ExitCommand:           "/exit",
		HooksInInteractive:    true,
		NeedsTrustSetup:       true,
		CanInject:             true,
		InjectionMethod:       "Stop hook additionalContext (not UserPromptSubmit)",
	},
	"pi": {
		Name: "pi", Binary: "pi",
		Install:  []string{"npm install -g --ignore-scripts @earendil-works/pi-coding-agent"},
		APIFormat: OpenAI, EndpointEnvVar: "", APIKeyEnvVar: "OPENROUTER_API_KEY",
		DefaultModel: "openai/gpt-4o-mini",
		HookFormat: TSExtension, EventCase: SnakeCase,
		HookConfigDir: ".pi/agent/extensions",
		Events: Events{
			SessionStart: "session_start", PromptSubmit: "before_agent_start",
			PostToolUse: "tool_result", Stop: "agent_end",
			PreCompact: "session_before_compact", SessionEnd: "session_shutdown",
		},
		HeadlessCmd:          []string{"pi", "-p"},
		HooksInHeadless:      true,
		InteractiveCmd:       []string{"pi"},
		ExitCommand:          "/exit",
		HooksInInteractive:   true,
		CanInject:            true,
		InjectionMethod:      "return {systemPrompt}",
	},
	"hermes": {
		Name: "hermes", Binary: "hermes",
		Install:  []string{"pip install hermes-agent"},
		APIFormat: OpenAI, EndpointEnvVar: "", APIKeyEnvVar: "OPENROUTER_API_KEY",
		DefaultModel: "openai/gpt-4o-mini",
		HookFormat: YAML, EventCase: SnakeCase,
		HookConfigDir: ".hermes",
		Events: Events{
			SessionStart: "on_session_start", PromptSubmit: "pre_llm_call",
			PreToolUse: "pre_tool_call", PostToolUse: "post_tool_call",
		},
		HeadlessCmd:           []string{"hermes", "-z"},
		HeadlessExtraFlags:    []string{"--accept-hooks", "--cli"},
		HooksInHeadless:       true,
		InteractiveCmd:        []string{"hermes"},
		ExitCommand:           "/exit",
		HooksInInteractive:    true,
		CanInject:             true,
		InjectionMethod:       `{"context":"..."}`,
	},
	"opencode": {
		Name: "opencode", Binary: "opencode",
		Install:  []string{"npm install -g opencode-ai"},
		APIFormat: OpenAI, EndpointEnvVar: "OPENAI_BASE_URL", APIKeyEnvVar: "OPENAI_API_KEY",
		DefaultModel: "gpt-4o-mini",
		HookFormat: TSPlugin, EventCase: CamelCase,
		HookConfigDir: ".config/opencode/plugins",
		Events: Events{
			PromptSubmit: "experimental.chat.system.transform",
		},
		SkillsDir:            ".config/opencode/skills",
		HeadlessCmd:           []string{"opencode", "run"},
		HooksInHeadless:       false,
		InteractiveCmd:        []string{"opencode"},
		ExitCommand:           "/exit",
		HooksInInteractive:    true,
		CanInject:             false,
		InjectionMethod:       "experimental.chat.system.transform (not working in headless)",
	},
	"mastracode": {
		Name: "mastracode", Binary: "mastracode",
		Install:  []string{"npm install -g mastracode"},
		APIFormat: OpenAI, EndpointEnvVar: "OPENAI_BASE_URL", APIKeyEnvVar: "OPENAI_API_KEY",
		HookFormat: JSONNested, EventCase: PascalCase,
		HookConfigDir: ".mastracode",
		Events: Events{
			SessionStart: "AgentStart", PreToolUse: "PreToolUse",
			PostToolUse: "PostToolUse", Stop: "Stop",
			SessionEnd: "AgentEnd",
		},
		HeadlessCmd:           []string{"mastracode", "--thread", "new"},
		HooksInHeadless:       false,
		InteractiveCmd:        []string{"mastracode"},
		ExitCommand:           "/exit",
		HooksInInteractive:    false,
		CanInject:             false,
		InjectionMethod:       "hooks are gate/logging only — no context injection",
	},
}
