package harness

var All = map[string]Harness{
	"claude": {
		Name: "claude", Binary: "claude",
		InstallCmd: []string{"npm", "install", "-g", "@anthropic-ai/claude-code"},
		APIFormat: Anthropic,
		EndpointEnvVars: map[string]string{
			"ANTHROPIC_BASE_URL": "{{.BaseURL}}",
		},
		APIKeyEnvVar: "ANTHROPIC_API_KEY",
		DefaultModel: "claude-haiku-4-5-20251001",
		HookFormat:    JSONNested,
		HookConfigDir: ".claude",
		HookFileName:  "settings.json",
		HookWrapper:   `{"permissions":{"allow":["Bash(*)","Read(*)","Write(*)"]},"skipDangerousModePermissionPrompt":true,"hooks":%s}`,
		ConfigFiles: []ConfigFile{
			{Path: ".claude.json", Content: `{"projects":{"{{.RepoDir}}":{"hasTrustDialogAccepted":true}}}`},
		},
		Events: Events{
			SessionStart: "SessionStart",
			PromptSubmit: "UserPromptSubmit",
			PreToolUse:   "PreToolUse",
			PostToolUse:  "PostToolUse",
			Stop:         "Stop",
			PreCompact:   "PreCompact",
		},
		SkillsDir:          ".claude/skills",
		HeadlessCmd:         []string{"claude", "-p"},
		HeadlessModelArgs:   []string{"--model", "{{.Model}}", "--dangerously-skip-permissions", "--max-turns", "1"},
		NeedsGitRepo:        true,
		HooksInHeadless:     true,
		InteractiveCmd:      []string{"claude"},
		ExitCommand:         "/exit",
		HooksInInteractive:  true,
		CanInject:           true,
	},
	"codex": {
		Name: "codex", Binary: "codex",
		InstallCmd: []string{"npm", "install", "-g", "@openai/codex"},
		PostInstall: [][]string{
			{"sh", "-c", "codex plugin marketplace add belt-sh-skills --source https://github.com/belt-sh/skills.git 2>/dev/null || true"},
			{"sh", "-c", "codex plugin add belt@belt-sh-skills 2>/dev/null || true"},
		},
		APIFormat: Responses,
		EndpointEnvVars: map[string]string{},
		APIKeyEnvVar:    "OPENAI_API_KEY",
		DefaultModel:    "gpt-4o-mini",
		HookFormat:      JSONNested,
		HookConfigDir:   ".codex",
		HookFileName:    "hooks.json",
		Events: Events{
			SessionStart: "SessionStart",
			PromptSubmit: "UserPromptSubmit",
			PreToolUse:   "PreToolUse",
			PostToolUse:  "PostToolUse",
			Stop:         "Stop",
			PreCompact:   "PreCompact",
		},
		PreserveHome:    true,
		SkillsDir:          ".agents/skills",
		HeadlessCmd:         []string{"codex", "exec"},
		HeadlessModelArgs: []string{
			"--dangerously-bypass-hook-trust",
			"-c", `model="{{.Model}}"`,
			"-c", `model_provider="mock"`,
			"-c", `model_providers.mock.name="Mock"`,
			"-c", `model_providers.mock.base_url="{{.BaseURL}}"`,
			"-c", `model_providers.mock.env_key="OPENAI_API_KEY"`,
			"-c", `model_providers.mock.wire_api="responses"`,
		},
		PromptViaStdin:      true,
		NeedsGitRepo:        true,
		HooksInHeadless:     true,
		InteractiveCmd:      []string{"codex"},
		ExitCommand:         "/exit",
		HooksInInteractive:  true,
		CanInject:           true,
	},
	"copilot": {
		Name: "copilot", Binary: "copilot",
		InstallCmd: []string{"npm", "install", "-g", "@github/copilot"},
		APIFormat: OpenAI,
		EndpointEnvVars: map[string]string{
			"COPILOT_PROVIDER_BASE_URL": "{{.BaseURL}}",
			"COPILOT_MODEL":            "{{.Model}}",
		},
		APIKeyEnvVar: "COPILOT_PROVIDER_API_KEY",
		DefaultModel: "gpt-4o-mini",
		HookFormat:    JSONCopilot,
		HookConfigDir: ".copilot/hooks",
		Events: Events{
			PromptSubmit: "userPromptSubmitted",
			Stop:         "agentStop",
		},
		SkillsDir:          ".copilot/skills",
		HeadlessCmd:         []string{"copilot", "--prompt"},
		HooksInHeadless:     true,
		InteractiveCmd:      []string{"copilot"},
		ExitCommand:         "/exit",
		HooksInInteractive:  true,
		CanInject:           true,
	},
	"grok": {
		Name: "grok", Binary: "grok",
		InstallCmd: []string{"sh", "-c", "curl -fsSL https://x.ai/cli/install.sh | bash"},
		APIFormat: OpenAI,
		EndpointEnvVars: map[string]string{
			"GROK_CLI_CHAT_PROXY_BASE_URL": "{{.BaseURL}}",
			"GROK_XAI_API_BASE_URL":        "{{.BaseURL}}",
			"GROK_MODELS_BASE_URL":          "{{.BaseURL}}",
			"GROK_FEEDBACK_BASE_URL":        "{{.BaseURL}}",
			"GROK_TRACE_UPLOAD_URL":         "{{.BaseURL}}",
			"GROK_MANAGED_CONFIG_URL":       "{{.BaseURL}}",
			"GROK_CONVERSATIONS_BASE_URL":   "{{.BaseURL}}",
		},
		APIKeyEnvVar: "XAI_API_KEY",
		DefaultModel: "grok-3-mini",
		HookFormat:    JSONNested,
		HookConfigDir: ".grok/hooks",
		Events: Events{
			PromptSubmit: "UserPromptSubmit",
			PreToolUse:   "PreToolUse",
			PostToolUse:  "PostToolUse",
			Stop:         "Stop",
		},
		ConfigFiles: []ConfigFile{
			{Path: ".grok/auth.json", Content: `{"https://auth.x.ai::b1a00492-073a-47ea-816f-4c329264a828":{"key":"mock-test-token","auth_mode":"oidc","create_time":"2026-01-01T00:00:00Z","user_id":"mock-user","email":"mock@test.invalid","expires_at":"2030-01-01T00:00:00Z","refresh_token":"mock-refresh-token","oidc_issuer":"https://auth.x.ai","oidc_client_id":"b1a00492-073a-47ea-816f-4c329264a828","coding_data_retention_opt_out":false}}`},
			{Path: ".grok/trusted_folders.toml", Content: "[folders.\"{{.RepoDir}}\"]\ntrusted = true\ndecided_at = 1786997000\n"},
		},
		SkillsDir:           ".grok/skills",
		HeadlessCmd:          []string{"grok", "-p"},
		HooksInHeadless:      false,
		InteractiveCmd:       []string{"grok", "--always-approve"},
		ExitCommand:          "/exit",
		HooksInInteractive:   true,
		CanInject:            true,
	},
	"pi": {
		Name: "pi", Binary: "pi",
		InstallCmd: []string{"npm", "install", "-g", "--ignore-scripts", "@earendil-works/pi-coding-agent"},
		APIFormat:    OpenAI,
		EndpointEnvVars: map[string]string{},
		APIKeyEnvVar: "OPENROUTER_API_KEY",
		DefaultModel: "openai/gpt-4o-mini",
		HookFormat:    TSExtension,
		HookConfigDir: ".pi/agent/extensions",
		Events:        Events{PromptSubmit: "before_agent_start", Stop: "agent_end"},
		HeadlessCmd:         []string{"pi", "-p"},
		HeadlessModelArgs:   []string{"--provider", "openrouter", "--model", "{{.Model}}", "--no-session"},
		HooksInHeadless:     true,
		InteractiveCmd:      []string{"pi"},
		ExitCommand:         "/exit",
		HooksInInteractive:  true,
		CanInject:           true,
	},
	"hermes": {
		Name: "hermes", Binary: "hermes",
		InstallCmd: []string{"pip", "install", "--break-system-packages", "hermes-agent"},
		APIFormat:    OpenAI,
		EndpointEnvVars: map[string]string{
			"OPENROUTER_BASE_URL": "{{.BaseURL}}/v1",
		},
		APIKeyEnvVar: "OPENROUTER_API_KEY",
		DefaultModel: "openai/gpt-4o-mini",
		HookFormat:    YAML,
		HookConfigDir: ".hermes",
		Events: Events{
			PromptSubmit: "pre_llm_call",
			PreToolUse:   "pre_tool_call",
			PostToolUse:  "post_tool_call",
			Stop:         "subagent_stop",
		},
		ConfigFiles: []ConfigFile{
			{Path: ".hermes/.env", Content: "OPENROUTER_API_KEY={{.APIKey}}\n"},
		},
		HeadlessCmd:          []string{"hermes", "chat", "-q"},
		HeadlessModelArgs:    []string{"-m", "{{.Model}}", "--provider", "openrouter", "--accept-hooks"},
		HooksInHeadless:      true,
		InteractiveCmd:       []string{"hermes"},
		ExitCommand:          "/exit",
		HooksInInteractive:   true,
		CanInject:            true,
	},
	"opencode": {
		Name: "opencode", Binary: "opencode",
		InstallCmd: []string{"npm", "install", "-g", "opencode-ai"},
		APIFormat: OpenAI,
		EndpointEnvVars: map[string]string{
			"OPENAI_BASE_URL": "{{.BaseURL}}/v1",
		},
		APIKeyEnvVar:    "OPENAI_API_KEY",
		DefaultModel:    "gpt-4o-mini",
		HookFormat:      TSPlugin,
		PreserveHome:    true,
		NeedsGitRepo:    true,
		HeadlessCmd:     []string{"opencode", "run"},
		HeadlessModelArgs: []string{"-m", "{{.Model}}", "--auto"},
		HooksInHeadless:     true,
		InteractiveCmd:      []string{"opencode"},
		ExitCommand:         "/exit",
		HooksInInteractive:  true,
		CanInject:           false,
	},
}
